# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Munizart
tagline:          "JavaScript and cheap talks"
description:      "Artur Muniz's personal blog, where I will be posting about front-end programming"
url:              https://muniz.art.br/

author:
  name:           "Artur Muniz"
  url:            "https://muniz.art.br/about"

paginate:         5

# Custom vars
version:          2.0.0
tracker:       "UA-74950243-3"
